# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/template_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 792)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        # self.table_social = QtWidgets.QTableView(self.layoutWidget)
        # self.table_social.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        # self.table_social.setObjectName("table_social")
        # self.verticalLayout.addWidget(self.table_social)
        self.verticalLayout_2.addWidget(self.splitter)
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_2.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(Form)
        self.btn_stop.setObjectName("btn_stop")
        self.verticalLayout_2.addWidget(self.btn_stop)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_start.setText(_translate("Form", "Start"))
        self.btn_stop.setText(_translate("Form", "Stop"))
